name: Markdown to PDF

on:
  push:
    branches: [master]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-tutoriels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pandoc
        run:
          sudo apt-get install pandoc && 
          sudo apt-get install texlive-latex-base
      - name: Convert to PDF
        run: ./.build/generate_tutoriels.sh
      - name: Upload out/ folder
        uses: actions/upload-artifact@v2
        with:
          name: tutoriels
          path: out/

