name: Markdown to PDF

on:
  push:
    branches: [master]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-tutoriels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pandoc
        run:
          sudo apt-get install pandoc && 
          sudo apt-get install texlive-latex-recommended
      - name: Convert to PDF
        run: ./.build/generate_tutoriels.sh
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: out/*
          makeLatest: true
