name: Markdown to PDF

on:
  push:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-tutoriels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Convert to PDF
        run: ./build/generate_tutoriels.sh
      - name: Upload out/ folder
        uses: actions/upload-artifact@v2
        with:
          name: tutoriels
          path: out/

