name: Markdown to PDF and Release

on:
  push:
    branches: [master]

jobs:
  build-tutoriels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pandoc
        run:
          sudo apt-get install pandoc && 
          sudo apt-get install texlive-latex-recommended && 
          sudo apt install texlive-formats-extra
      - name: Convert to PDF
        run: ./.build/generate_tutoriels.sh
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: out/*
          tag: ${{ github.run_number }}
          name: Tutoriels - ${{ github.run_number }}
          makeLatest: true
